## -*- encoding: utf-8 -*-
## This file ("Parallel Covariance and Variance Calculation Paper".sagetex.sage) was *autogenerated* from "Parallel Covariance and Variance Calculation Paper".tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('"Parallel Covariance and Variance Calculation Paper"', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.endofdoc()
